apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apiopbanca-virtual-services
spec:
  hosts:
    - "apiopbanca.vs"
  gateways:
    - http-gateway                      # 1
  http:
    - route:
        - destination:
            host: apiopbanca
            port:
              number: 8090