apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiseguridad
spec:
  selector:
    matchLabels:
      app: apiseguridad
  replicas: 1
  template:
    metadata:
      labels:
        app: apiseguridad
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
      - name: apiseguridad
        image: msalvadorp/apiseguridad
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: apiseguridad
  labels:
    app: apiseguridad
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: http-trafic
  selector:
    app: apiseguridad
  #type: LoadBalancer