apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiseguridad
spec:
  selector:
    matchLabels:
      app: apiseguridad
  replicas: 2
  template:
    metadata:
      labels:
        app: apiseguridad
    spec:
      containers:
      - name: apiseguridad
        image: msalvadorp/apiseguridad
        imagePullPolicy: Always
        ports:
        - containerPort: 8081